version: '3.9'

services:
    nodejs:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: aprex-node-container
        depends_on:
            - database
        ports:
            - '80:8000'
        command: >
            sh -c "sh deploy.sh"
        volumes:
            - '.:/srv:cached'

    database:
        image: 'mariadb:10.7.3'
        container_name: aprex-database-container
        restart: 'on-failure'
        volumes:
            - '.:/srv:cached'
        ports:
            - "3306:3306"
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: aprex-api

    phpmyadmin:
        image: phpmyadmin
        container_name: aprex-phpmyadmin-container
        restart: always
        ports:
            - 8080:80
        links:
            - 'database'
        environment:
            - PMA_ARBITRARY=1

networks: 
    default:
        name: aprex-back-network